Redefining numbers notations in Quack
quack/quack pull request #83
Opened 2016-11-07 08:07 UTC by luizperes

This PR makes Quack numbers consistent by changing some rules. Thus, we do not use PHP notation anymore.

There are numerous inconsistencies in PHP such as:
  - Hexadecimal notation can be represented by `0xFFfff0` and `0XFFfff0`
  - Binary notation is only represented by `0b0001` (`0B0001` is not valid).
  - Octal notation is weird: `0666` (__?__) `// isn't that a decimal notation number?`

This PR is redefining Quack numbers to:

|              | Decimal |  Binary | Octal | Hexadecimal  | Double | Double Exp |
| :--------: | :---------: | :----------: | :------: | :------: | :----------------: | :--------------: |
| __Then__  |  2222   | 0`[bB]`10011010  | 0765  | 0`[xX]`FA19  |  3.1415  |  - |
| __Now__  |   2222 |  0`b`10011010 |  0`o`765   | 0`x`FA19  |  3.1415  | 2.15`e[+-]`10 |

In order to ease our future tasks of analysing number types (such as comparison optimizations and reducing the complexity of always checking a number), I included new `Tag` types: `T_INT_OCT`, `T_INT_BIN`, `T_INT_HEX` and `T_DOUBLE_EXP`. Thus, I also created a member named `notation` inside the `NumberExpr` class. Having said that, `octal`, `binary` and `hexadecimal` notation numbers are still __int__ and `scientific` notation ones are __double__.

Obs.: If we took `Quack` only as a Transpiler, we wouldn't need to check those numbers, however, the Quack project is big and I am thinking about the future implications of not having those tags. 

------------------------------------------------------------------
- `digit()` is now using the `KMP` algorithm approach for the `octal`, `binary` and `hexadecimal` notations.

 - The second part (checking for floating numbers) uses a basic state machine:

![photo435744009096374236](https://cloud.githubusercontent.com/assets/6173065/20050420/1a68da88-a47e-11e6-903c-2d6733fe80c5.jpg)

2017-02-08 23:34 UTC, haskellcamargo requested changes

2017-02-08 23:34 UTC, haskellcamargo commented on src/lexer/Tokenizer.php
> +        if (!$this->isEnd() && ($this->matches('e+') || $this->matches('e-'))
When only `e` is found, we also have a valid positive form.

2017-02-09 06:16 UTC, luizperes commented on src/lexer/Tokenizer.php
> +        if (!$this->isEnd() && ($this->matches('e+') || $this->matches('e-'))
will do it!

2017-02-09 07:00 UTC, luizperes commented on src/lexer/Tokenizer.php
> +        if (!$this->isEnd() && ($this->matches('e+') || $this->matches('e-'))
I have just done it! Please check that out @haskellcamargo

2017-02-09 10:53 UTC, haskellcamargo approved these changes

2017-02-09 10:53 UTC, haskellcamargo commented
Definitely LGTM!

2017-02-09 16:25 UTC, merged

2017-02-10 05:43 UTC, luizperes commented
yay!